### ISSUE TITLE
Support Compose Multiplatform?

### ISSUE THREAD

**Issue by sunny-chung** [jaikeerthick/Composable-Graphs#32]
Would you support Compose Multiplatform?

I just have a quick look on the source code. It seems the core does not depend on Android-specific stuffs, so it might not be difficult. If you have no time, would you accept a PR?

**Comment by jaikeerthick** [comment]
Hey @sunny-chung, Thank you for your interest in Composable Graphs library. Yes the library doesn't depend on Android-specific things. Adding support for Compose Multiplatform sounds like a valuable addition, and I appreciate your willingness to contribute.

I'm open to accepting a pull request (PR) for this feature if you're willing to work on it. Feel free to go ahead and submit a PR whenever you're ready. If you have any questions or need guidance along the way, don't hesitate to ask. Your contribution to the project is greatly appreciated!

**Comment by sunny-chung** [comment]
I can do that, but there will be a breaking change for you. Jitpack does not build Apple OS artifacts. To support multiplatform, perhaps you would have to move to Maven Central, which requires you to changing the library group ID to "io.github.jaikeerthick".

**Comment by jaikeerthick** [comment]
I understand the requirements and challenges to migrate to KMM. The library still need to mature a lot and therefore I'm planning to not to support KMM as of now and I promise that the library will continue to have pure kotlin code and no Android-specific dependencies so that in future It'll be easy to support KMM.

Thanks.
